# Generated by Django 5.0.1 on 2025-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temoignages', '0002_questionnaire_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temoin',
            name='fichier_video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
