# Generated by Django 5.0.1 on 2025-06-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temoignages', '0005_alter_questionnaire_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
