# Generated by Django 5.0.1 on 2025-07-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Temoignages', '0009_alter_questionnaire_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
